FROM ruby:3.2.2

# Install dependencies
RUN apt-get update -qq && \
    apt-get install -y postgresql-client nodejs && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy Gemfile
COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle install

# Copy the rest of the application
COPY . .

# Expose port 5000
EXPOSE 5000

# Start server
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "5000"]
